### PR TITLE
Poll tabs bug

### LINKED ISSUE #126: Poll tabs affect Comment tabs
Changing tab in the polls (mods only) changes active tab in comments to something non-existent (only in this direction, polls tab won't change if comment tab changed)
image

### PR DESCRIPTION
**Pull request by alpacawren**
### Before you begin

* I understand my contributions may be rejected for any reason
* I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
* I understand my contributions are licensed under the GNU AGPLv3

- [x] I understand all of the above

---

Fixes #126

### CODE REVIEW

File: assets/js/boorujs.js [hunk 1]
```diff
@@ -81,6 +83,14 @@ function selectorCb(base = document, selector, cb) {
   [].forEach.call(base.querySelectorAll(selector), cb);
 }
 
+function selectorCbChildren(base = document, selector, cb) {
+  var sel = Array.from(base.querySelectorAll(selector));
```
Comment (liamwhite) [inline assets/js/boorujs.js:87]: I think it's a bit cleaner if you do it this way
```js
const sel = $$(selector, base);

for (const el of base.children) {
  if (!sel.includes(el)) continue;

  cb(sel);
}
```
